#! /usr/bin/env bash

set -euo pipefail

echo -e "\n# Generated by scripts/gen_filelist.sh\n"

echo "target_sources(prog PRIVATE"
# make paths relative to the project root, surround with quotes and add a tab for readability
find . -name "*.cpp" | sort | sed -e "s/^.\\//\t\".\\/src\\//" -e "s/$/\"/"
find . -name "*.c" | sort | sed -e "s/^.\\//\t\".\\/src\\//" -e "s/$/\"/"
echo -e ")\n"

