
# Generated by scripts/gen_filelist.sh

target_sources(prog PRIVATE
	"./src/algorithm.c"
	"./src/cache.c"
	"./src/cliparse.c"
	"./src/main.c"
	"./src/pattern.c"
	"./src/userio.c"
	"./src/wordlist.c"
)

