
# Generated by scripts/gen_filelist.sh

target_sources(internal PRIVATE
	"./src/algorithm.c"
	"./src/argparse.c"
	"./src/cache.c"
	"./src/config.c"
	"./src/fsutils.c"
	"./src/main.c"
	"./src/pattern.c"
	"./src/solver.c"
	"./src/userio.c"
	"./src/wordlemodule.c"
	"./src/wordlist.c"
)

