
# Generated by scripts/gen_filelist.sh

target_sources(modules PRIVATE
	"./src/algorithm.c"
	"./src/cache.c"
	"./src/config.c"
	"./src/fsutils.c"
	"./src/pattern.c"
	"./src/userio.c"
	"./src/wordlist.c"
)

