
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")

set(CPACK_BINARY_DEB "ON")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TZ "ON")

set(CPACK_PACKAGE_CONTACT "https://github.com/Arnav814")

set(CPACK_DEBIAN_PACKAGE_SECTION "games")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libncursesw6")
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64") # TODO: support other architectures

